# Generated by Django 4.2.5 on 2023-09-30 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_patient_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='registered_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registration date'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateTimeField(verbose_name='Date of birth'),
        ),
    ]
