# Generated by Django 4.2.5 on 2023-09-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_patient_registered_at_alter_patient_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Other', 'OTHER')], max_length=200),
        ),
    ]
